# Setup
setup: single_task

# Database
train_db_name: PROSPECT
val_db_name: PROSPECT
trBatch: 512
valBatch: 512
nworkers: 4

# Optimizer and scheduler
epochs: 100
optimizer: adam
optimizer_kwargs:
   lr: 0.001
   weight_decay: 0.0001
scheduler: poly

# Model
model: baseline
backbone: resnet18
head: MLP

backbone_kwargs:
    dilated: False

# Tasks
task_dictionary:
    Cab: True

# Loss kwargs
loss_kwargs:
   loss_scheme: baseline
   loss_weights:
       Cab: 1.0
